language: c

before_install: 
   - export ROOT_DIR=`pwd`
   - sudo apt-get update -qq
   - sudo apt-get install -y mpich2 libmpich2-dev 

env:
  matrix:
    - TEST=comm_test
    - TEST=crs_test
    - TEST=crystal_test
    - TEST=findpts_el_2_test
    - TEST=findpts_el_2_test2
    - TEST=findpts_el_3_test
    - TEST=findpts_el_3_test2
    - TEST=findpts_local_test
    - TEST=findpts_test
    - TEST=gs_test
    - TEST=gs_test_old
    - TEST=gs_unique_test
    - TEST=lob_bnd_test
    - TEST=obbox_test
    - TEST=poly_test
    - TEST=poly_test2
    - TEST=sarray_sort_test
    - TEST=sarray_transfer_test
    - TEST=sort_test
    - TEST=sort_test2
    - TEST=spchol_test
    - TEST=xxt_test
    - TEST=xxt_test2

install: true

script:
  - cd $ROOT_DIR/src
  - make CC=mpicc $TEST
  - mpiexec -np 2 ./$TEST
